version: '3'

env:
  MONGO_URI: 'mongodb://root:kasper123@localhost'

tasks:
  setup:
    desc: "setup web-interface"
    cmds:
      - cd ./frontend && npm install
      - cd ./backend && virtualenv .env
      - cd ./backend && (source .env/bin/activate;
          pip3 install -r requirements.txt)

  frontend:
    desc: "start the web-interface frontend server"
    dir: ./frontend
    cmds:
      - npm start

  build-frontend:
    desc: "build the frontend bundle.js"
    dir: ./frontend
    cmds:
      - npm run build

  copy-bundle:
    desc: "copy bundle.js into backend"
    cmds:
      - cp frontend/dist/bundle.js backend/static

  backend:
    desc: "start the web-interface backend server"
    dir: ./backend
    cmds:
      - task: build-frontend
      - task: copy-bundle
      - (source .env/bin/activate;
         python3 app.py)
