# Use postgres/example user/password credentials
version: '3.1'

services:
  web-interface:
    build: web-interface
    restart: always
    environment:
      MONGO_URI: mongodb://root:kasper123@db
    ports:
      - 5001:5001

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kasper123
    ports:
      - 27017:27017
